services:
  db:
    image: postgres:17-alpine
    container_name: db
    environment:
      - POSTGRES_USER=nxr
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=gym
    ports:
      - '5431:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
  test-db:
    image: postgres:17-alpine
    container_name: test-db
    environment:
      - POSTGRES_USER=nxr
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=gym
    ports:
      - '5430:5432'

volumes:
  pg_data:
